/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type UserAccessRequest = {
  _id: string;
  _type: "userAccessRequest";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  clerkUserId?: string;
  email?: string;
  firstName?: string;
  lastName?: string;
  status?: "pending" | "approved" | "rejected";
  requestedAt?: string;
  approvedAt?: string;
  approvedBy?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "user";
  };
  rejectedAt?: string;
  rejectedBy?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "user";
  };
  notes?: string;
};

export type Subscription = {
  _id: string;
  _type: "subscription";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  email?: string;
  status?: "active" | "unsubscribed" | "pending";
  subscribedAt?: string;
  unsubscribedAt?: string;
  source?: "footer" | "popup" | "checkout" | "other";
  ipAddress?: string;
  userAgent?: string;
};

export type SentNotification = {
  _id: string;
  _type: "sentNotification";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  notificationId?: string;
  title?: string;
  message?: string;
  type?: "promo" | "order" | "system" | "marketing" | "general";
  priority?: "low" | "medium" | "high" | "urgent";
  sentAt?: string;
  sentBy?: string;
  actionUrl?: string;
  recipientCount?: number;
  recipients?: Array<{
    email?: string;
    name?: string;
    delivered?: boolean;
    read?: boolean;
    readAt?: string;
    _key: string;
  }>;
};

export type Review = {
  _id: string;
  _type: "review";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  product?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "product";
  };
  user?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "user";
  };
  rating?: number;
  title?: string;
  content?: string;
  isVerifiedPurchase?: boolean;
  status?: "pending" | "approved" | "rejected";
  helpful?: number;
  helpfulBy?: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "user";
  }>;
  adminNotes?: string;
  createdAt?: string;
  updatedAt?: string;
  approvedAt?: string;
  approvedBy?: string;
};

export type ProductWeight = {
  _id: string;
  _type: "productWeight";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  value?: string;
  unit?: "g" | "kg" | "lb" | "oz";
  numericValue?: number;
  isActive?: boolean;
  weight?: number;
  description?: string;
};

export type ProductSize = {
  _id: string;
  _type: "productSize";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  value?: string;
  isActive?: boolean;
  weight?: number;
  description?: string;
};

export type ProductColor = {
  _id: string;
  _type: "productColor";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  hexCode?: string;
  isActive?: boolean;
  weight?: number;
  description?: string;
};

export type Personel = {
  _id: string;
  _type: "personel";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  firebaseUid?: string;
  email?: string;
  firstName?: string;
  lastName?: string;
  phone?: string;
  dateOfBirth?: string;
  addresses?: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "address";
  }>;
  isEmployee?: boolean;
  employeeRole?: "callcenter" | "packer" | "warehouse" | "deliveryman" | "incharge" | "accounts";
  employeeStatus?: "active" | "inactive" | "suspended";
  employeeAssignedBy?: string;
  employeeAssignedAt?: string;
  employeeSuspendedBy?: string;
  employeeSuspendedAt?: string;
  employeeSuspensionReason?: string;
  createdAt?: string;
  updatedAt?: string;
};

export type Order = {
  _id: string;
  _type: "order";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  store?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "store";
  };
  orderNumber?: string;
  items?: Array<{
    product?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "product";
    };
    quantity?: number;
    priceAtPurchase?: number;
    _key: string;
  }>;
  total?: number;
  status?: "paid" | "shipped" | "delivered" | "cancelled";
  customer?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "customer";
  };
  clerkUserId?: string;
  email?: string;
  address?: {
    name?: string;
    line1?: string;
    line2?: string;
    city?: string;
    postcode?: string;
    country?: string;
  };
  paychanguPaymentId?: string;
  createdAt?: string;
};

export type Customer = {
  _id: string;
  _type: "customer";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  store?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "store";
  };
  email?: string;
  name?: string;
  clerkUserId?: string;
  paychanguCustomerId?: string;
  paychanguStatus?: "active" | "pending" | "disabled";
  createdAt?: string;
};

export type Store = {
  _id: string;
  _type: "store";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  image?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  address?: {
    street?: string;
    house?: string;
    city?: string;
    state?: string;
    zipCode?: string;
    country?: "MW" | "ZA" | "TZ" | "MZ";
  };
  coordinates?: {
    lat?: number;
    lng?: number;
  };
  contact?: {
    phone?: string;
    email?: string;
  };
  hours?: {
    monday?: {
      open?: string;
      close?: string;
      closed?: boolean;
    };
    tuesday?: {
      open?: string;
      close?: string;
      closed?: boolean;
    };
    wednesday?: {
      open?: string;
      close?: string;
      closed?: boolean;
    };
    thursday?: {
      open?: string;
      close?: string;
      closed?: boolean;
    };
    friday?: {
      open?: string;
      close?: string;
      closed?: boolean;
    };
    saturday?: {
      open?: string;
      close?: string;
      closed?: boolean;
    };
    sunday?: {
      open?: string;
      close?: string;
      closed?: boolean;
    };
  };
  description?: string;
  features?: Array<string>;
  isActive?: boolean;
  sortOrder?: number;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type Coupon = {
  _id: string;
  _type: "coupon";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  code?: string;
  description?: string;
  discountType?: "percentage" | "fixed";
  discountValue?: number;
  minimumOrderAmount?: number;
  maxDiscountAmount?: number;
  usageLimit?: number;
  usageLimitPerUser?: number;
  timesUsed?: number;
  startDate?: string;
  expiryDate?: string;
  isActive?: boolean;
  isPublic?: boolean;
  applicableProducts?: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "product";
  }>;
  applicableCategories?: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "category";
  }>;
  excludedProducts?: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "product";
  }>;
  firstOrderOnly?: boolean;
  userRestrictions?: Array<string>;
  createdAt?: string;
};

export type Contact = {
  _id: string;
  _type: "contact";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  email?: string;
  subject?: string;
  message?: string;
  status?: "new" | "read" | "replied" | "closed";
  priority?: "low" | "medium" | "high" | "urgent";
  submittedAt?: string;
  ipAddress?: string;
  userAgent?: string;
};

export type Category = {
  _id: string;
  _type: "category";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
};

export type BusinessProduct = {
  _id: string;
  _type: "businessProduct";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  businessEmail?: string;
  businessName?: string;
  name?: string;
  slug?: Slug;
  images?: Array<{
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
    _key: string;
  }>;
  description?: string;
  price?: number;
  baseWeight?: number;
  discount?: number;
  categories?: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "category";
  }>;
  stock?: number;
  brand?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "brand";
  };
  variant?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "productVariant";
  };
  hasWeights?: boolean;
  hasBrand?: boolean;
  useAllWeights?: boolean;
  weights?: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "productWeight";
  }>;
  hasVariants?: boolean;
  useAllSizes?: boolean;
  sizes?: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "productSize";
  }>;
  useAllColors?: boolean;
  colors?: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "productColor";
  }>;
  profitMargin?: number;
  businessProductStatus?: "draft" | "pending" | "approved" | "rejected" | "active" | "inactive" | "pending_deactivation" | "pending_activation";
  approvalStatus?: "awaiting" | "approved" | "rejected";
  rejectionReason?: string;
  submittedAt?: string;
  approvedAt?: string;
  approvedBy?: string;
  mainProductId?: string;
  totalSales?: number;
  totalRevenue?: number;
  totalProfit?: number;
  lastOrderDate?: string;
};

export type ProductVariant = {
  _id: string;
  _type: "productVariant";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  description?: string;
  isActive?: boolean;
  weight?: number;
  seoTitle?: string;
  seoDescription?: string;
};

export type BusinessApplication = {
  _id: string;
  _type: "businessApplication";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  user?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "user";
  };
  userId?: string;
  userEmail?: string;
  businessName?: string;
  businessType?: "individual" | "informal" | "partnership" | "llc" | "corporation" | "cooperative" | "nonprofit" | "community" | "digital" | "other";
  businessDescription?: string;
  businessAddress?: string;
  businessPhone?: string;
  businessEmail?: string;
  taxId?: string;
  websiteUrl?: string;
  productsCategory?: "produce" | "grains" | "meat_fish" | "dairy" | "packaged_foods" | "beverages" | "fashion" | "footwear_accessories" | "electronics" | "phones" | "home_kitchen" | "furniture" | "building_materials" | "agro_supplies" | "beauty" | "health" | "education" | "crafts" | "services" | "digital_products" | "wholesale" | "other";
  estimatedMonthlyRevenue?: "0-499999" | "750000-1249999" | "1250000-2499999" | "2500000-4999999" | "5000000-9999999" | "10000000+";
  status?: "pending" | "reviewing" | "approved" | "rejected";
  appliedAt?: string;
  reviewedAt?: string;
  reviewedBy?: string;
  approvalNotes?: string;
  rejectionReason?: string;
  adminNotes?: string;
};

export type Blog = {
  _id: string;
  _type: "blog";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  author?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "author";
  };
  mainImage?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  blogcategories?: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "blogcategory";
  }>;
  publishedAt?: string;
  isLatest?: boolean;
  body?: BlockContent;
};

export type BlockContent = Array<{
  children?: Array<{
    marks?: Array<string>;
    text?: string;
    _type: "span";
    _key: string;
  }>;
  style?: "normal" | "h1" | "h2" | "h3" | "h4" | "blockquote";
  listItem?: "bullet";
  markDefs?: Array<{
    href?: string;
    _type: "link";
    _key: string;
  }>;
  level?: number;
  _type: "block";
  _key: string;
} | {
  asset?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
  };
  media?: unknown;
  hotspot?: SanityImageHotspot;
  crop?: SanityImageCrop;
  alt?: string;
  _type: "image";
  _key: string;
}>;

export type Blogcategory = {
  _id: string;
  _type: "blogcategory";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  description?: string;
};

export type Banner = {
  _id: string;
  _type: "banner";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  image?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  title?: string;
  buttonTitle?: string;
  buttonHref?: string;
};

export type Author = {
  _id: string;
  _type: "author";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  image?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  bio?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal";
    listItem?: never;
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
};

export type Address = {
  _id: string;
  _type: "address";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  email?: string;
  user?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "user";
  };
  phone?: string;
  address?: string;
  city?: string;
  state?: string;
  zip?: string;
  country?: string;
  countryCode?: string;
  stateCode?: string;
  subArea?: string;
  type?: "home" | "office" | "other";
  default?: boolean;
  createdAt?: string;
};

export type User = {
  _id: string;
  _type: "user";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  firebaseUid?: string;
  email?: string;
  firstName?: string;
  lastName?: string;
  phone?: string;
  dateOfBirth?: string;
  profileImage?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  profileImageUrl?: string;
  addresses?: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "address";
  }>;
  preferences?: {
    newsletter?: boolean;
    emailNotifications?: boolean;
    smsNotifications?: boolean;
    preferredCurrency?: "MWK" | "USD" | "EUR" | "GBP" | "CAD";
    preferredLanguage?: "en" | "ch" | "es" | "fr" | "de";
  };
  rewardPoints?: number;
  wishlist?: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "product";
  }>;
  cart?: Array<{
    product?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "product";
    };
    quantity?: number;
    addedAt?: string;
    size?: string;
    color?: string;
    _key: string;
  }>;
  orders?: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "order";
  }>;
  loyaltyPoints?: number;
  totalSpent?: number;
  walletBalance?: number;
  walletTransactions?: Array<{
    id?: string;
    type?: "credit_refund" | "credit_manual" | "debit_order" | "debit_withdrawal";
    amount?: number;
    balanceBefore?: number;
    balanceAfter?: number;
    description?: string;
    orderId?: string;
    withdrawalRequestId?: string;
    processedBy?: string;
    createdAt?: string;
    status?: "completed" | "pending" | "failed" | "cancelled";
    _key: string;
  }>;
  withdrawalRequests?: Array<{
    id?: string;
    amount?: number;
    method?: "bank" | "paypal" | "stripe" | "check";
    bankDetails?: {
      accountHolderName?: string;
      bankName?: string;
      accountNumber?: string;
      routingNumber?: string;
      swiftCode?: string;
    };
    paypalEmail?: string;
    status?: "pending" | "approved" | "processing" | "completed" | "rejected" | "cancelled";
    requestedAt?: string;
    processedAt?: string;
    processedBy?: string;
    rejectionReason?: string;
    notes?: string;
    transactionId?: string;
    _key: string;
  }>;
  lastLogin?: string;
  isActive?: boolean;
  isBusiness?: boolean;
  businessStatus?: "none" | "pending" | "active" | "rejected" | "suspended";
  businessAppliedAt?: string;
  businessApprovedBy?: string;
  businessApprovedAt?: string;
  businessRejectedAt?: string;
  businessRejectionReason?: string;
  businessSuspendedAt?: string;
  businessSuspendedBy?: string;
  businessSuspensionReason?: string;
  businessName?: string;
  businessDescription?: string;
  businessLogo?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  businessCommissionRate?: number;
  businessPerformance?: {
    totalProducts?: number;
    activeProducts?: number;
    totalSales?: number;
    totalRevenue?: number;
    totalCommission?: number;
    averageRating?: number;
    totalReviews?: number;
  };
  isAdmin?: boolean;
  createdAt?: string;
  updatedAt?: string;
  notifications?: Array<{
    id?: string;
    title?: string;
    message?: string;
    type?: "promo" | "order" | "system" | "marketing" | "general";
    read?: boolean;
    priority?: "low" | "medium" | "high" | "urgent";
    sentAt?: string;
    readAt?: string;
    sentBy?: string;
    actionUrl?: string;
    _key: string;
  }>;
};

export type Product = {
  _id: string;
  _type: "product";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  images?: Array<{
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
    _key: string;
  }>;
  description?: string;
  price?: number;
  discount?: number;
  stock?: number;
  categories?: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "category";
  }>;
  status?: "new" | "hot" | "sale";
  hasBrand?: boolean;
  brand?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "brand";
  };
  isElectronic?: boolean;
  electronicDetails?: {
    model?: string;
    warrantyMonths?: number;
    isDevice?: boolean;
    specs?: {
      ram?: string;
      storage?: string;
      batteryCapacity?: number;
      batteryHealth?: number;
    };
  };
  isClothing?: boolean;
  clothingDetails?: {
    sizes?: Array<{
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      _key: string;
      [internalGroqTypeReferenceTo]?: "productSize";
    }>;
    colors?: Array<{
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      _key: string;
      [internalGroqTypeReferenceTo]?: "productColor";
    }>;
    material?: string;
    gender?: "Men" | "Women" | "Unisex" | "Kids";
  };
  isConsumable?: boolean;
  consumableDetails?: {
    weights?: Array<{
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      _key: string;
      [internalGroqTypeReferenceTo]?: "productWeight";
    }>;
    expiryDate?: string;
    batchNumber?: string;
    isPerishable?: boolean;
  };
  isMaterial?: boolean;
  materialDetails?: {
    materialType?: string;
    grade?: string;
    weights?: Array<{
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      _key: string;
      [internalGroqTypeReferenceTo]?: "productWeight";
    }>;
  };
  isFeatured?: boolean;
  isOffer?: boolean;
  enableRatingsManagement?: boolean;
  averageRating?: number;
  totalReviews?: number;
  ratingDistribution?: {
    fiveStars?: number;
    fourStars?: number;
    threeStars?: number;
    twoStars?: number;
    oneStar?: number;
  };
};

export type Brand = {
  _id: string;
  _type: "brand";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  description?: string;
  image?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes = UserAccessRequest | Subscription | SentNotification | Review | ProductWeight | ProductSize | ProductColor | Personel | Order | Customer | Store | SanityImageCrop | SanityImageHotspot | Slug | Coupon | Contact | Category | BusinessProduct | ProductVariant | BusinessApplication | Blog | BlockContent | Blogcategory | Banner | Author | Address | User | Product | Brand | SanityImagePaletteSwatch | SanityImagePalette | SanityImageDimensions | SanityImageMetadata | SanityFileAsset | SanityAssetSourceData | SanityImageAsset | Geopoint;
export declare const internalGroqTypeReferenceTo: unique symbol;
// Source: ./sanity/queries/banners.ts
// Variable: BANNERS_QUERY
// Query: *[_type == "banner"] | order(_createdAt desc) {      _id,      title,      buttonTitle,      buttonHref,      image {        asset->{          url        }      }    }
export type BANNERS_QUERYResult = Array<{
  _id: string;
  title: string | null;
  buttonTitle: string | null;
  buttonHref: string | null;
  image: {
    asset: {
      url: string | null;
    } | null;
  } | null;
}>;

// Source: ./sanity/queries/blogs.ts
// Variable: LATEST_BLOG_QUERY
// Query: *[_type == 'blog' && isLatest == true]|order(name asc){            ...,            blogcategories[]->{            title        }    }
export type LATEST_BLOG_QUERYResult = Array<{
  _id: string;
  _type: "blog";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  author?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "author";
  };
  mainImage?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  blogcategories: Array<{
    title: string | null;
  }> | null;
  publishedAt?: string;
  isLatest?: boolean;
  body?: BlockContent;
}>;
// Variable: GET_ALL_BLOG
// Query: *[_type == 'blog'] | order(publishedAt desc)[0...$quantity]{            ...,            author->{                name,                image,            },            blogcategories[]->{                title            }      }
export type GET_ALL_BLOGResult = Array<{
  _id: string;
  _type: "blog";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  author: {
    name: string | null;
    image: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    } | null;
  } | null;
  mainImage?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  blogcategories: Array<{
    title: string | null;
  }> | null;
  publishedAt?: string;
  isLatest?: boolean;
  body?: BlockContent;
}>;
// Variable: SINGLE_BLOG_QUERY
// Query: *[_type == "blog" && slug.current == $slug][0]{        ...,         author->{        name,        image,    },    blogcategories[]->{        title,        "slug": slug.current,    },}
export type SINGLE_BLOG_QUERYResult = {
  _id: string;
  _type: "blog";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  author: {
    name: string | null;
    image: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    } | null;
  } | null;
  mainImage?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  blogcategories: Array<{
    title: string | null;
    slug: string | null;
  }> | null;
  publishedAt?: string;
  isLatest?: boolean;
  body?: BlockContent;
} | null;
// Variable: BLOG_CATEGORIES
// Query: *[_type == "blog"]{            blogcategories[]->{            ...        }    }
export type BLOG_CATEGORIESResult = Array<{
  blogcategories: Array<{
    _id: string;
    _type: "blogcategory";
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    title?: string;
    slug?: Slug;
    description?: string;
  }> | null;
}>;
// Variable: OTHERS_BLOG_QUERY
// Query: *[    _type == "blog"    && defined(slug.current)    && slug.current != $slug    ]|order(publishedAt desc)[0...$quantity]{        _id,        publishedAt,        title,        mainImage,        slug,        author->{            name,            image,        },        categories[]->{            title,            "slug": slug.current,        }}
export type OTHERS_BLOG_QUERYResult = Array<{
  _id: string;
  publishedAt: string | null;
  title: string | null;
  mainImage: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  slug: Slug | null;
  author: {
    name: string | null;
    image: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    } | null;
  } | null;
  categories: null;
}>;

// Source: ./sanity/queries/categories.ts
// Variable: ALL_CATEGORIES_QUERY
// Query: *[  _type == "category"] | order(title asc) {  _id,  title,  "slug": slug.current,  "image": image{    asset->{      _id,      url    },    hotspot  }}
export type ALL_CATEGORIES_QUERYResult = Array<{
  _id: string;
  title: string | null;
  slug: string | null;
  image: null;
}>;
// Variable: CATEGORY_BY_SLUG_QUERY
// Query: *[  _type == "category"  && slug.current == $slug][0] {  _id,  title,  "slug": slug.current,  "image": image{    asset->{      _id,      url    },    hotspot  }}
export type CATEGORY_BY_SLUG_QUERYResult = {
  _id: string;
  title: string | null;
  slug: string | null;
  image: null;
} | null;

// Source: ./sanity/queries/customers.ts
// Variable: CUSTOMER_BY_EMAIL_QUERY
// Query: *[  _type == "customer"  && email == $email][0]{  _id,  email,  name,  clerkUserId,  stripeCustomerId,  createdAt}
export type CUSTOMER_BY_EMAIL_QUERYResult = {
  _id: string;
  email: string | null;
  name: string | null;
  clerkUserId: string | null;
  stripeCustomerId: null;
  createdAt: string | null;
} | null;
// Variable: CUSTOMER_BY_STRIPE_ID_QUERY
// Query: *[  _type == "customer"  && stripeCustomerId == $stripeCustomerId][0]{  _id,  email,  name,  clerkUserId,  stripeCustomerId,  createdAt}
export type CUSTOMER_BY_STRIPE_ID_QUERYResult = {
  _id: string;
  email: string | null;
  name: string | null;
  clerkUserId: string | null;
  stripeCustomerId: null;
  createdAt: string | null;
} | null;

// Source: ./sanity/queries/orders.ts
// Variable: ORDERS_BY_USER_QUERY
// Query: *[  _type == "order"  && clerkUserId == $clerkUserId] | order(createdAt desc) {  _id,  orderNumber,  total,  status,  createdAt,  "itemCount": count(items),  "itemNames": items[].product->name,  "itemImages": items[].product->images[0].asset->url}
export type ORDERS_BY_USER_QUERYResult = Array<{
  _id: string;
  orderNumber: string | null;
  total: number | null;
  status: "cancelled" | "delivered" | "paid" | "shipped" | null;
  createdAt: string | null;
  itemCount: number | null;
  itemNames: Array<string | null> | null;
  itemImages: Array<string | null> | null;
}>;
// Variable: ORDER_BY_ID_QUERY
// Query: *[  _type == "order"  && _id == $id][0] {  _id,  orderNumber,  clerkUserId,  email,  items[]{    _key,    quantity,    priceAtPurchase,    product->{      _id,      name,      "slug": slug.current,      "image": images[0]{        asset->{          _id,          url        }      }    }  },  total,  status,  address{    name,    line1,    line2,    city,    postcode,    country  },  stripePaymentId,  createdAt}
export type ORDER_BY_ID_QUERYResult = {
  _id: string;
  orderNumber: string | null;
  clerkUserId: string | null;
  email: string | null;
  items: Array<{
    _key: string;
    quantity: number | null;
    priceAtPurchase: number | null;
    product: {
      _id: string;
      name: string | null;
      slug: string | null;
      image: {
        asset: {
          _id: string;
          url: string | null;
        } | null;
      } | null;
    } | null;
  }> | null;
  total: number | null;
  status: "cancelled" | "delivered" | "paid" | "shipped" | null;
  address: {
    name: string | null;
    line1: string | null;
    line2: string | null;
    city: string | null;
    postcode: string | null;
    country: string | null;
  } | null;
  stripePaymentId: null;
  createdAt: string | null;
} | null;
// Variable: RECENT_ORDERS_QUERY
// Query: *[  _type == "order"] | order(createdAt desc) [0...$limit] {  _id,  orderNumber,  email,  total,  status,  createdAt}
export type RECENT_ORDERS_QUERYResult = Array<{
  _id: string;
  orderNumber: string | null;
  email: string | null;
  total: number | null;
  status: "cancelled" | "delivered" | "paid" | "shipped" | null;
  createdAt: string | null;
}>;
// Variable: ORDER_BY_STRIPE_PAYMENT_ID_QUERY
// Query: *[  _type == "order"  && stripePaymentId == $stripePaymentId][0]{ _id }
export type ORDER_BY_STRIPE_PAYMENT_ID_QUERYResult = {
  _id: string;
} | null;

// Source: ./sanity/queries/products.ts
// Variable: PRODUCT_COUNT_BY_USER_QUERY
// Query: count(    *[      _type == "product"      && store->userId == $userId    ]  )
export type PRODUCT_COUNT_BY_USER_QUERYResult = number;
// Variable: PRODUCTS_BY_STORE_QUERY
// Query: *[  _type == "product"  && store._ref == $storeId]  | order(_createdAt desc) {    _id,    name,    price,    stock,    featured,    "slug": slug.current,    images[0]{ asset->{ url } }  }
export type PRODUCTS_BY_STORE_QUERYResult = Array<{
  _id: string;
  name: string | null;
  price: number | null;
  stock: number | null;
  featured: null;
  slug: string | null;
  images: {
    asset: {
      url: string | null;
    } | null;
  } | null;
}>;
// Variable: ALL_PRODUCTS_QUERY
// Query: *[  _type == "product"] | order(name asc) {  _id,  name,  "slug": slug.current,  description,  price,  "images": images[]{    _key,    asset->{      _id,      url    },    hotspot  },  categories[0]->{    _id,    title,    "slug": slug.current  },  material,  color,  dimensions,  stock,  featured,  assemblyRequired}
export type ALL_PRODUCTS_QUERYResult = Array<{
  _id: string;
  name: string | null;
  slug: string | null;
  description: string | null;
  price: number | null;
  images: Array<{
    _key: string;
    asset: {
      _id: string;
      url: string | null;
    } | null;
    hotspot: SanityImageHotspot | null;
  }> | null;
  categories: {
    _id: string;
    title: string | null;
    slug: string | null;
  } | null;
  material: null;
  color: null;
  dimensions: null;
  stock: number | null;
  featured: null;
  assemblyRequired: null;
}>;
// Variable: FEATURED_PRODUCTS_QUERY
// Query: *[    _type == "product" &&    defined(description) &&    count(categories) > 0 &&    enableRatingsManagement == true &&    averageRating > 4.5  ]{    _id,name,description,"slug": slug.current,price,discount,stock,status,isFeatured,isOffer,"images": images[]{  asset->{url},  hotspot},    categories[]->{      title,      "slug": slug.current    }  }
export type FEATURED_PRODUCTS_QUERYResult = Array<{
  _id: string;
  name: string | null;
  description: string | null;
  slug: string | null;
  price: number | null;
  discount: number | null;
  stock: number | null;
  status: "hot" | "new" | "sale" | null;
  isFeatured: boolean | null;
  isOffer: boolean | null;
  images: Array<{
    asset: {
      url: string | null;
    } | null;
    hotspot: SanityImageHotspot | null;
  }> | null;
  categories: Array<{
    title: string | null;
    slug: string | null;
  }> | null;
}>;
// Variable: PRODUCTS_BY_CATEGORY_QUERY
// Query: *[  _type == "product"  && categories[0]->slug.current == $categorySlug] | order(name asc) {  _id,  name,  "slug": slug.current,  price,  "image": images[0]{    asset->{      _id,      url    },    hotspot  },  categories[0]->{    _id,    title,    "slug": slug.current  },  material,  color,  stock}
export type PRODUCTS_BY_CATEGORY_QUERYResult = Array<{
  _id: string;
  name: string | null;
  slug: string | null;
  price: number | null;
  image: {
    asset: {
      _id: string;
      url: string | null;
    } | null;
    hotspot: SanityImageHotspot | null;
  } | null;
  categories: {
    _id: string;
    title: string | null;
    slug: string | null;
  } | null;
  material: null;
  color: null;
  stock: number | null;
}>;
// Variable: PRODUCT_BY_SLUG_QUERY
// Query: *[    _type == "product"    && slug.current == $slug  ][0]{    _id,    name,    "slug": slug.current,    description,    price,    discount,    stock,    status,    isFeatured,    isOffer,    images[]{      _key,      asset->{ _id, url },      hotspot    },    categories[]->{      _id,      title,      "slug": slug.current    },    hasBrand,    brand->{      _id,      name,      "slug": slug.current    },    isElectronic,    electronicDetails,    isClothing,    clothingDetails,    isConsumable,    consumableDetails,    isMaterial,    materialDetails,    enableRatingsManagement,    averageRating,    totalReviews,    ratingDistribution,    store->{      _id,      name,      username,      logo{        asset->{ _id, url }      }    }  }
export type PRODUCT_BY_SLUG_QUERYResult = {
  _id: string;
  name: string | null;
  slug: string | null;
  description: string | null;
  price: number | null;
  discount: number | null;
  stock: number | null;
  status: "hot" | "new" | "sale" | null;
  isFeatured: boolean | null;
  isOffer: boolean | null;
  images: Array<{
    _key: string;
    asset: {
      _id: string;
      url: string | null;
    } | null;
    hotspot: SanityImageHotspot | null;
  }> | null;
  categories: Array<{
    _id: string;
    title: string | null;
    slug: string | null;
  }> | null;
  hasBrand: boolean | null;
  brand: {
    _id: string;
    name: null;
    slug: string | null;
  } | null;
  isElectronic: boolean | null;
  electronicDetails: {
    model?: string;
    warrantyMonths?: number;
    isDevice?: boolean;
    specs?: {
      ram?: string;
      storage?: string;
      batteryCapacity?: number;
      batteryHealth?: number;
    };
  } | null;
  isClothing: boolean | null;
  clothingDetails: {
    sizes?: Array<{
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      _key: string;
      [internalGroqTypeReferenceTo]?: "productSize";
    }>;
    colors?: Array<{
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      _key: string;
      [internalGroqTypeReferenceTo]?: "productColor";
    }>;
    material?: string;
    gender?: "Kids" | "Men" | "Unisex" | "Women";
  } | null;
  isConsumable: boolean | null;
  consumableDetails: {
    weights?: Array<{
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      _key: string;
      [internalGroqTypeReferenceTo]?: "productWeight";
    }>;
    expiryDate?: string;
    batchNumber?: string;
    isPerishable?: boolean;
  } | null;
  isMaterial: boolean | null;
  materialDetails: {
    materialType?: string;
    grade?: string;
    weights?: Array<{
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      _key: string;
      [internalGroqTypeReferenceTo]?: "productWeight";
    }>;
  } | null;
  enableRatingsManagement: boolean | null;
  averageRating: number | null;
  totalReviews: number | null;
  ratingDistribution: {
    fiveStars?: number;
    fourStars?: number;
    threeStars?: number;
    twoStars?: number;
    oneStar?: number;
  } | null;
  store: null;
} | null;
// Variable: SEARCH_PRODUCTS_QUERY
// Query: *[  _type == "product"  && (    name match $searchQuery + "*"    || description match $searchQuery + "*"  )] | score(  boost(name match $searchQuery + "*", 3),  boost(description match $searchQuery + "*", 1)) | order(_score desc) {  _id,  _score,  store->{    _id,    name,    username,    logo{      asset->{        _id,        url      }    }  },  name,  "slug": slug.current,  price,  "image": images[0]{    asset->{      _id,      url    },    hotspot  },  categories[0]->{    _id,    title,    "slug": slug.current  },  stock}
export type SEARCH_PRODUCTS_QUERYResult = Array<{
  _id: string;
  _score: null;
  store: null;
  name: string | null;
  slug: string | null;
  price: number | null;
  image: {
    asset: {
      _id: string;
      url: string | null;
    } | null;
    hotspot: SanityImageHotspot | null;
  } | null;
  categories: {
    _id: string;
    title: string | null;
    slug: string | null;
  } | null;
  stock: number | null;
}>;
// Variable: FILTER_PRODUCTS_BY_NAME_QUERY
// Query: *[  _type == "product"  && ($categorySlug == "" || categories[0]->slug.current == $categorySlug)  && ($minPrice == 0 || price >= $minPrice)  && ($maxPrice == 0 || price <= $maxPrice)  && (    $searchQuery == ""    || name match $searchQuery + "*"    || description match $searchQuery + "*"    || categories[0]->title match $searchQuery + "*"  )  && ($inStock == false || stock > 0)]  | order(name asc)  {      _id,  name,  "slug": slug.current,  price,  discount,  stock,  status,  isFeatured,  isOffer,  "images": images[0...4]{    _key,    asset->{ _id, url }  },  categories[]->{    _id,    title,    "slug": slug.current  }  }
export type FILTER_PRODUCTS_BY_NAME_QUERYResult = Array<{
  _id: string;
  name: string | null;
  slug: string | null;
  price: number | null;
  discount: number | null;
  stock: number | null;
  status: "hot" | "new" | "sale" | null;
  isFeatured: boolean | null;
  isOffer: boolean | null;
  images: Array<{
    _key: string;
    asset: {
      _id: string;
      url: string | null;
    } | null;
  }> | null;
  categories: Array<{
    _id: string;
    title: string | null;
    slug: string | null;
  }> | null;
}>;
// Variable: FILTER_PRODUCTS_BY_PRICE_ASC_QUERY
// Query: *[  _type == "product"  && ($categorySlug == "" || categories[0]->slug.current == $categorySlug)  && ($minPrice == 0 || price >= $minPrice)  && ($maxPrice == 0 || price <= $maxPrice)  && (    $searchQuery == ""    || name match $searchQuery + "*"    || description match $searchQuery + "*"    || categories[0]->title match $searchQuery + "*"  )  && ($inStock == false || stock > 0)]  | order(price asc)  {      _id,  name,  "slug": slug.current,  price,  discount,  stock,  status,  isFeatured,  isOffer,  "images": images[0...4]{    _key,    asset->{ _id, url }  },  categories[]->{    _id,    title,    "slug": slug.current  }  }
export type FILTER_PRODUCTS_BY_PRICE_ASC_QUERYResult = Array<{
  _id: string;
  name: string | null;
  slug: string | null;
  price: number | null;
  discount: number | null;
  stock: number | null;
  status: "hot" | "new" | "sale" | null;
  isFeatured: boolean | null;
  isOffer: boolean | null;
  images: Array<{
    _key: string;
    asset: {
      _id: string;
      url: string | null;
    } | null;
  }> | null;
  categories: Array<{
    _id: string;
    title: string | null;
    slug: string | null;
  }> | null;
}>;
// Variable: FILTER_PRODUCTS_BY_PRICE_DESC_QUERY
// Query: *[  _type == "product"  && ($categorySlug == "" || categories[0]->slug.current == $categorySlug)  && ($minPrice == 0 || price >= $minPrice)  && ($maxPrice == 0 || price <= $maxPrice)  && (    $searchQuery == ""    || name match $searchQuery + "*"    || description match $searchQuery + "*"    || categories[0]->title match $searchQuery + "*"  )  && ($inStock == false || stock > 0)]  | order(price desc)  {      _id,  name,  "slug": slug.current,  price,  discount,  stock,  status,  isFeatured,  isOffer,  "images": images[0...4]{    _key,    asset->{ _id, url }  },  categories[]->{    _id,    title,    "slug": slug.current  }  }
export type FILTER_PRODUCTS_BY_PRICE_DESC_QUERYResult = Array<{
  _id: string;
  name: string | null;
  slug: string | null;
  price: number | null;
  discount: number | null;
  stock: number | null;
  status: "hot" | "new" | "sale" | null;
  isFeatured: boolean | null;
  isOffer: boolean | null;
  images: Array<{
    _key: string;
    asset: {
      _id: string;
      url: string | null;
    } | null;
  }> | null;
  categories: Array<{
    _id: string;
    title: string | null;
    slug: string | null;
  }> | null;
}>;
// Variable: FILTER_PRODUCTS_BY_RELEVANCE_QUERY
// Query: *[  _type == "product"  && ($categorySlug == "" || categories[0]->slug.current == $categorySlug)  && ($minPrice == 0 || price >= $minPrice)  && ($maxPrice == 0 || price <= $maxPrice)  && (    $searchQuery == ""    || name match $searchQuery + "*"    || description match $searchQuery + "*"    || categories[0]->title match $searchQuery + "*"  )  && ($inStock == false || stock > 0)]  | score(  boost(name match $searchQuery + "*", 3),  boost(description match $searchQuery + "*", 1),  boost(categories[0]->title match $searchQuery + "*", 1))  | order(_score desc, name asc)  {      _id,  name,  "slug": slug.current,  price,  discount,  stock,  status,  isFeatured,  isOffer,  "images": images[0...4]{    _key,    asset->{ _id, url }  },  categories[]->{    _id,    title,    "slug": slug.current  }  }
export type FILTER_PRODUCTS_BY_RELEVANCE_QUERYResult = Array<{
  _id: string;
  name: string | null;
  slug: string | null;
  price: number | null;
  discount: number | null;
  stock: number | null;
  status: "hot" | "new" | "sale" | null;
  isFeatured: boolean | null;
  isOffer: boolean | null;
  images: Array<{
    _key: string;
    asset: {
      _id: string;
      url: string | null;
    } | null;
  }> | null;
  categories: Array<{
    _id: string;
    title: string | null;
    slug: string | null;
  }> | null;
}>;
// Variable: PRODUCTS_BY_IDS_QUERY
// Query: *[  _type == "product"  && _id in $ids] {  _id,  store->{    _id,    name,    username,    logo{      asset->{        _id,        url      }    }  },  name,  "slug": slug.current,  price,  "image": images[0]{    asset->{      _id,      url    },    hotspot  },  stock}
export type PRODUCTS_BY_IDS_QUERYResult = Array<{
  _id: string;
  store: null;
  name: string | null;
  slug: string | null;
  price: number | null;
  image: {
    asset: {
      _id: string;
      url: string | null;
    } | null;
    hotspot: SanityImageHotspot | null;
  } | null;
  stock: number | null;
}>;
// Variable: LOW_STOCK_PRODUCTS_QUERY
// Query: *[      _type == "product"  && store._ref == $storeId    && stock > 0    && stock <= 5  ]  | order(stock asc) {    _id,    name,    stock,    "slug": slug.current,    images[0]{ asset->{ url } }  }
export type LOW_STOCK_PRODUCTS_QUERYResult = Array<{
  _id: string;
  name: string | null;
  stock: number | null;
  slug: string | null;
  images: {
    asset: {
      url: string | null;
    } | null;
  } | null;
}>;
// Variable: OUT_OF_STOCK_PRODUCTS_QUERY
// Query: *[      _type == "product"  && store._ref == $storeId    && stock == 0  ]  | order(name asc) {    _id,    name,    "slug": slug.current,    images[0]{ asset->{ url } }  }
export type OUT_OF_STOCK_PRODUCTS_QUERYResult = Array<{
  _id: string;
  name: string | null;
  slug: string | null;
  images: {
    asset: {
      url: string | null;
    } | null;
  } | null;
}>;
// Variable: AI_SEARCH_PRODUCTS_QUERY
// Query: *[  _type == "product"  && (    $searchQuery == ""    || name match $searchQuery + "*"    || description match $searchQuery + "*"    || categories[0]->title match $searchQuery + "*"  )  && ($categorySlug == "" || categories[0]->slug.current == $categorySlug)  && ($material == "" || material == $material)  && ($color == "" || color == $color)  && ($minPrice == 0 || price >= $minPrice)  && ($maxPrice == 0 || price <= $maxPrice)] | order(name asc) [0...20] {  _id,  store->{    _id,    name,    username,    logo{      asset->{        _id,        url      }    }  },  name,  "slug": slug.current,  description,  price,  "image": images[0]{    asset->{      _id,      url    }  },  categories[0]->{    _id,    title,    "slug": slug.current  },  stock,  featured}
export type AI_SEARCH_PRODUCTS_QUERYResult = Array<{
  _id: string;
  store: null;
  name: string | null;
  slug: string | null;
  description: string | null;
  price: number | null;
  image: {
    asset: {
      _id: string;
      url: string | null;
    } | null;
  } | null;
  categories: {
    _id: string;
    title: string | null;
    slug: string | null;
  } | null;
  stock: number | null;
  featured: null;
}>;

// Source: ./sanity/queries/stats.ts
// Variable: PRODUCT_COUNT_QUERY
// Query: count(*[_type == "product"])
export type PRODUCT_COUNT_QUERYResult = number;
// Variable: ORDER_COUNT_QUERY
// Query: count(*[_type == "order"])
export type ORDER_COUNT_QUERYResult = number;
// Variable: TOTAL_REVENUE_QUERY
// Query: math::sum(*[  _type == "order"  && status in ["paid", "shipped", "delivered"]].total)
export type TOTAL_REVENUE_QUERYResult = number;
// Variable: ORDERS_LAST_7_DAYS_QUERY
// Query: *[  _type == "order"  && createdAt >= $startDate  && !(_id in path("drafts.**"))] | order(createdAt desc) {  _id,  orderNumber,  total,  status,  createdAt,  "itemCount": count(items),  items[]{    quantity,    priceAtPurchase,    "productName": product->name,    "productId": product->_id  }}
export type ORDERS_LAST_7_DAYS_QUERYResult = Array<{
  _id: string;
  orderNumber: string | null;
  total: number | null;
  status: "cancelled" | "delivered" | "paid" | "shipped" | null;
  createdAt: string | null;
  itemCount: number | null;
  items: Array<{
    quantity: number | null;
    priceAtPurchase: number | null;
    productName: string | null;
    productId: string | null;
  }> | null;
}>;
// Variable: ORDER_STATUS_DISTRIBUTION_QUERY
// Query: {  "paid": count(*[_type == "order" && status == "paid" && !(_id in path("drafts.**"))]),  "shipped": count(*[_type == "order" && status == "shipped" && !(_id in path("drafts.**"))]),  "delivered": count(*[_type == "order" && status == "delivered" && !(_id in path("drafts.**"))]),  "cancelled": count(*[_type == "order" && status == "cancelled" && !(_id in path("drafts.**"))])}
export type ORDER_STATUS_DISTRIBUTION_QUERYResult = {
  paid: number;
  shipped: number;
  delivered: number;
  cancelled: number;
};
// Variable: TOP_SELLING_PRODUCTS_QUERY
// Query: *[  _type == "order"  && status in ["paid", "shipped", "delivered"]  && !(_id in path("drafts.**"))] {  items[]{    "productId": product->_id,    "productName": product->name,    "productPrice": product->price,    quantity  }}.items[]
export type TOP_SELLING_PRODUCTS_QUERYResult = Array<{
  productId: string | null;
  productName: string | null;
  productPrice: number | null;
  quantity: number | null;
} | null>;
// Variable: PRODUCTS_INVENTORY_QUERY
// Query: *[_type == "product"] {  _id,  name,  price,  stock,  "category": categories[0]->title}
export type PRODUCTS_INVENTORY_QUERYResult = Array<{
  _id: string;
  name: string | null;
  price: number | null;
  stock: number | null;
  category: string | null;
}>;
// Variable: UNFULFILLED_ORDERS_QUERY
// Query: *[  _type == "order"  && status == "paid"  && !(_id in path("drafts.**"))] | order(createdAt asc) {  _id,  orderNumber,  total,  createdAt,  email,  "itemCount": count(items)}
export type UNFULFILLED_ORDERS_QUERYResult = Array<{
  _id: string;
  orderNumber: string | null;
  total: number | null;
  createdAt: string | null;
  email: string | null;
  itemCount: number | null;
}>;
// Variable: REVENUE_BY_PERIOD_QUERY
// Query: {  "currentPeriod": math::sum(*[    _type == "order"    && status in ["paid", "shipped", "delivered"]    && createdAt >= $currentStart    && !(_id in path("drafts.**"))  ].total),  "previousPeriod": math::sum(*[    _type == "order"    && status in ["paid", "shipped", "delivered"]    && createdAt >= $previousStart    && createdAt < $currentStart    && !(_id in path("drafts.**"))  ].total),  "currentOrderCount": count(*[    _type == "order"    && createdAt >= $currentStart    && !(_id in path("drafts.**"))  ]),  "previousOrderCount": count(*[    _type == "order"    && createdAt >= $previousStart    && createdAt < $currentStart    && !(_id in path("drafts.**"))  ])}
export type REVENUE_BY_PERIOD_QUERYResult = {
  currentPeriod: number;
  previousPeriod: number;
  currentOrderCount: number;
  previousOrderCount: number;
};

// Source: ./sanity/queries/store.ts
// Variable: STORE_BY_USERNAME_QUERY
// Query: *[_type == "store" && username == $username && activated == true][0]{    _id,    name,    description,    username,    address,    email,    contact,    status,    activated,    keywords,    categories,    types,    "slug": slug.current,    logo {      asset->{        _id,        url      }    }  }
export type STORE_BY_USERNAME_QUERYResult = null;
// Variable: ALL_ACTIVE_STORES_QUERY
// Query: *[_type == "store" && activated == true] | order(_createdAt desc){    _id,    name,    username,    description,    categories,    types,    "slug": slug.current,    logo {      asset->{        _id,        url      }    }  }
export type ALL_ACTIVE_STORES_QUERYResult = Array<never>;
// Variable: STORES_BY_USER_QUERY
// Query: *[_type == "store" && userId == $userId] | order(_createdAt desc){    _id,    userId,    name,    username,    status,    activated,    categories,    types,    "slug": slug.current,    logo {      asset->{        _id,        url      }    }  }
export type STORES_BY_USER_QUERYResult = Array<{
  _id: string;
  userId: null;
  name: string | null;
  username: null;
  status: null;
  activated: null;
  categories: null;
  types: null;
  slug: string | null;
  logo: null;
}>;
// Variable: STORE_BY_SLUG_QUERY
// Query: *[_type == "store" && slug.current == $slug][0]{    _id,    name,    description,    username,    address,    email,    contact,    status,    activated,    keywords,    categories,    types,    userId,    "slug": slug.current,    logo {      asset->{        _id,        url      }    }  }
export type STORE_BY_SLUG_QUERYResult = {
  _id: string;
  name: string | null;
  description: string | null;
  username: null;
  address: {
    street?: string;
    house?: string;
    city?: string;
    state?: string;
    zipCode?: string;
    country?: "MW" | "MZ" | "TZ" | "ZA";
  } | null;
  email: null;
  contact: {
    phone?: string;
    email?: string;
  } | null;
  status: null;
  activated: null;
  keywords: null;
  categories: null;
  types: null;
  userId: null;
  slug: string | null;
  logo: null;
} | null;
// Variable: STORE_EXISTS_BY_USERNAME_QUERY
// Query: count(*[_type == "store" && username == $username])
export type STORE_EXISTS_BY_USERNAME_QUERYResult = number;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    "\n    *[_type == \"banner\"] | order(_createdAt desc) {\n      _id,\n      title,\n      buttonTitle,\n      buttonHref,\n      image {\n        asset->{\n          url\n        }\n      }\n    }\n": BANNERS_QUERYResult;
    " *[_type == 'blog' && isLatest == true]|order(name asc){\n            ...,\n            blogcategories[]->{\n            title\n        }\n    }": LATEST_BLOG_QUERYResult;
    "*[_type == 'blog'] | order(publishedAt desc)[0...$quantity]{\n            ...,\n            author->{\n                name,\n                image,\n            },\n            blogcategories[]->{\n                title\n            }\n      }\n    ": GET_ALL_BLOGResult;
    "*[_type == \"blog\" && slug.current == $slug][0]{\n        ..., \n        author->{\n        name,\n        image,\n    },\n    blogcategories[]->{\n        title,\n        \"slug\": slug.current,\n    },\n}": SINGLE_BLOG_QUERYResult;
    "*[_type == \"blog\"]{\n            blogcategories[]->{\n            ...\n        }\n    }": BLOG_CATEGORIESResult;
    "*[\n    _type == \"blog\"\n    && defined(slug.current)\n    && slug.current != $slug\n    ]|order(publishedAt desc)[0...$quantity]{\n        _id,\n        publishedAt,\n        title,\n        mainImage,\n        slug,\n        author->{\n            name,\n            image,\n        },\n        categories[]->{\n            title,\n            \"slug\": slug.current,\n        }\n}": OTHERS_BLOG_QUERYResult;
    "*[\n  _type == \"category\"\n] | order(title asc) {\n  _id,\n  title,\n  \"slug\": slug.current,\n  \"image\": image{\n    asset->{\n      _id,\n      url\n    },\n    hotspot\n  }\n}": ALL_CATEGORIES_QUERYResult;
    "*[\n  _type == \"category\"\n  && slug.current == $slug\n][0] {\n  _id,\n  title,\n  \"slug\": slug.current,\n  \"image\": image{\n    asset->{\n      _id,\n      url\n    },\n    hotspot\n  }\n}": CATEGORY_BY_SLUG_QUERYResult;
    "*[\n  _type == \"customer\"\n  && email == $email\n][0]{\n  _id,\n  email,\n  name,\n  clerkUserId,\n  stripeCustomerId,\n  createdAt\n}": CUSTOMER_BY_EMAIL_QUERYResult;
    "*[\n  _type == \"customer\"\n  && stripeCustomerId == $stripeCustomerId\n][0]{\n  _id,\n  email,\n  name,\n  clerkUserId,\n  stripeCustomerId,\n  createdAt\n}": CUSTOMER_BY_STRIPE_ID_QUERYResult;
    "*[\n  _type == \"order\"\n  && clerkUserId == $clerkUserId\n] | order(createdAt desc) {\n  _id,\n  orderNumber,\n  total,\n  status,\n  createdAt,\n  \"itemCount\": count(items),\n  \"itemNames\": items[].product->name,\n  \"itemImages\": items[].product->images[0].asset->url\n}": ORDERS_BY_USER_QUERYResult;
    "*[\n  _type == \"order\"\n  && _id == $id\n][0] {\n  _id,\n  orderNumber,\n  clerkUserId,\n  email,\n  items[]{\n    _key,\n    quantity,\n    priceAtPurchase,\n    product->{\n      _id,\n      name,\n      \"slug\": slug.current,\n      \"image\": images[0]{\n        asset->{\n          _id,\n          url\n        }\n      }\n    }\n  },\n  total,\n  status,\n  address{\n    name,\n    line1,\n    line2,\n    city,\n    postcode,\n    country\n  },\n  stripePaymentId,\n  createdAt\n}": ORDER_BY_ID_QUERYResult;
    "*[\n  _type == \"order\"\n] | order(createdAt desc) [0...$limit] {\n  _id,\n  orderNumber,\n  email,\n  total,\n  status,\n  createdAt\n}": RECENT_ORDERS_QUERYResult;
    "*[\n  _type == \"order\"\n  && stripePaymentId == $stripePaymentId\n][0]{ _id }": ORDER_BY_STRIPE_PAYMENT_ID_QUERYResult;
    "\n  count(\n    *[\n      _type == \"product\"\n      && store->userId == $userId\n    ]\n  )\n": PRODUCT_COUNT_BY_USER_QUERYResult;
    "\n  *[\n  _type == \"product\"\n  && store._ref == $storeId\n]\n  | order(_createdAt desc) {\n    _id,\n    name,\n    price,\n    stock,\n    featured,\n    \"slug\": slug.current,\n    images[0]{ asset->{ url } }\n  }\n": PRODUCTS_BY_STORE_QUERYResult;
    "*[\n  _type == \"product\"\n] | order(name asc) {\n  _id,\n  name,\n  \"slug\": slug.current,\n  description,\n  price,\n  \"images\": images[]{\n    _key,\n    asset->{\n      _id,\n      url\n    },\n    hotspot\n  },\n  categories[0]->{\n    _id,\n    title,\n    \"slug\": slug.current\n  },\n  material,\n  color,\n  dimensions,\n  stock,\n  featured,\n  assemblyRequired\n}": ALL_PRODUCTS_QUERYResult;
    "\n  *[\n    _type == \"product\" &&\n    defined(description) &&\n    count(categories) > 0 &&\n    enableRatingsManagement == true &&\n    averageRating > 4.5\n  ]{\n    \n_id,\nname,\ndescription,\n\"slug\": slug.current,\nprice,\ndiscount,\nstock,\nstatus,\nisFeatured,\nisOffer,\n\"images\": images[]{\n  asset->{url},\n  hotspot\n}\n,\n    categories[]->{\n      title,\n      \"slug\": slug.current\n    }\n  }\n": FEATURED_PRODUCTS_QUERYResult;
    "*[\n  _type == \"product\"\n  && categories[0]->slug.current == $categorySlug\n] | order(name asc) {\n  _id,\n  name,\n  \"slug\": slug.current,\n  price,\n  \"image\": images[0]{\n    asset->{\n      _id,\n      url\n    },\n    hotspot\n  },\n  categories[0]->{\n    _id,\n    title,\n    \"slug\": slug.current\n  },\n  material,\n  color,\n  stock\n}": PRODUCTS_BY_CATEGORY_QUERYResult;
    "\n  *[\n    _type == \"product\"\n    && slug.current == $slug\n  ][0]{\n    _id,\n    name,\n    \"slug\": slug.current,\n    description,\n    price,\n    discount,\n    stock,\n    status,\n    isFeatured,\n    isOffer,\n\n    images[]{\n      _key,\n      asset->{ _id, url },\n      hotspot\n    },\n\n    categories[]->{\n      _id,\n      title,\n      \"slug\": slug.current\n    },\n\n    hasBrand,\n    brand->{\n      _id,\n      name,\n      \"slug\": slug.current\n    },\n\n    isElectronic,\n    electronicDetails,\n\n    isClothing,\n    clothingDetails,\n\n    isConsumable,\n    consumableDetails,\n\n    isMaterial,\n    materialDetails,\n\n    enableRatingsManagement,\n    averageRating,\n    totalReviews,\n    ratingDistribution,\n\n    store->{\n      _id,\n      name,\n      username,\n      logo{\n        asset->{ _id, url }\n      }\n    }\n  }\n": PRODUCT_BY_SLUG_QUERYResult;
    "*[\n  _type == \"product\"\n  && (\n    name match $searchQuery + \"*\"\n    || description match $searchQuery + \"*\"\n  )\n] | score(\n  boost(name match $searchQuery + \"*\", 3),\n  boost(description match $searchQuery + \"*\", 1)\n) | order(_score desc) {\n  _id,\n  _score,\n  store->{\n    _id,\n    name,\n    username,\n    logo{\n      asset->{\n        _id,\n        url\n      }\n    }\n  },\n  name,\n  \"slug\": slug.current,\n  price,\n  \"image\": images[0]{\n    asset->{\n      _id,\n      url\n    },\n    hotspot\n  },\n  categories[0]->{\n    _id,\n    title,\n    \"slug\": slug.current\n  },\n  stock\n}": SEARCH_PRODUCTS_QUERYResult;
    "\n  *[\n  _type == \"product\"\n  && ($categorySlug == \"\" || categories[0]->slug.current == $categorySlug)\n  && ($minPrice == 0 || price >= $minPrice)\n  && ($maxPrice == 0 || price <= $maxPrice)\n  && (\n    $searchQuery == \"\"\n    || name match $searchQuery + \"*\"\n    || description match $searchQuery + \"*\"\n    || categories[0]->title match $searchQuery + \"*\"\n  )\n  && ($inStock == false || stock > 0)\n]\n  | order(name asc)\n  {\n    \n  _id,\n  name,\n  \"slug\": slug.current,\n  price,\n  discount,\n  stock,\n  status,\n  isFeatured,\n  isOffer,\n\n  \"images\": images[0...4]{\n    _key,\n    asset->{ _id, url }\n  },\n\n  categories[]->{\n    _id,\n    title,\n    \"slug\": slug.current\n  }\n\n  }\n": FILTER_PRODUCTS_BY_NAME_QUERYResult;
    "\n  *[\n  _type == \"product\"\n  && ($categorySlug == \"\" || categories[0]->slug.current == $categorySlug)\n  && ($minPrice == 0 || price >= $minPrice)\n  && ($maxPrice == 0 || price <= $maxPrice)\n  && (\n    $searchQuery == \"\"\n    || name match $searchQuery + \"*\"\n    || description match $searchQuery + \"*\"\n    || categories[0]->title match $searchQuery + \"*\"\n  )\n  && ($inStock == false || stock > 0)\n]\n  | order(price asc)\n  {\n    \n  _id,\n  name,\n  \"slug\": slug.current,\n  price,\n  discount,\n  stock,\n  status,\n  isFeatured,\n  isOffer,\n\n  \"images\": images[0...4]{\n    _key,\n    asset->{ _id, url }\n  },\n\n  categories[]->{\n    _id,\n    title,\n    \"slug\": slug.current\n  }\n\n  }\n": FILTER_PRODUCTS_BY_PRICE_ASC_QUERYResult;
    "\n  *[\n  _type == \"product\"\n  && ($categorySlug == \"\" || categories[0]->slug.current == $categorySlug)\n  && ($minPrice == 0 || price >= $minPrice)\n  && ($maxPrice == 0 || price <= $maxPrice)\n  && (\n    $searchQuery == \"\"\n    || name match $searchQuery + \"*\"\n    || description match $searchQuery + \"*\"\n    || categories[0]->title match $searchQuery + \"*\"\n  )\n  && ($inStock == false || stock > 0)\n]\n  | order(price desc)\n  {\n    \n  _id,\n  name,\n  \"slug\": slug.current,\n  price,\n  discount,\n  stock,\n  status,\n  isFeatured,\n  isOffer,\n\n  \"images\": images[0...4]{\n    _key,\n    asset->{ _id, url }\n  },\n\n  categories[]->{\n    _id,\n    title,\n    \"slug\": slug.current\n  }\n\n  }\n": FILTER_PRODUCTS_BY_PRICE_DESC_QUERYResult;
    "\n  *[\n  _type == \"product\"\n  && ($categorySlug == \"\" || categories[0]->slug.current == $categorySlug)\n  && ($minPrice == 0 || price >= $minPrice)\n  && ($maxPrice == 0 || price <= $maxPrice)\n  && (\n    $searchQuery == \"\"\n    || name match $searchQuery + \"*\"\n    || description match $searchQuery + \"*\"\n    || categories[0]->title match $searchQuery + \"*\"\n  )\n  && ($inStock == false || stock > 0)\n]\n  | score(\n  boost(name match $searchQuery + \"*\", 3),\n  boost(description match $searchQuery + \"*\", 1),\n  boost(categories[0]->title match $searchQuery + \"*\", 1)\n)\n  | order(_score desc, name asc)\n  {\n    \n  _id,\n  name,\n  \"slug\": slug.current,\n  price,\n  discount,\n  stock,\n  status,\n  isFeatured,\n  isOffer,\n\n  \"images\": images[0...4]{\n    _key,\n    asset->{ _id, url }\n  },\n\n  categories[]->{\n    _id,\n    title,\n    \"slug\": slug.current\n  }\n\n  }\n": FILTER_PRODUCTS_BY_RELEVANCE_QUERYResult;
    "*[\n  _type == \"product\"\n  && _id in $ids\n] {\n  _id,\n  store->{\n    _id,\n    name,\n    username,\n    logo{\n      asset->{\n        _id,\n        url\n      }\n    }\n  },\n  name,\n  \"slug\": slug.current,\n  price,\n  \"image\": images[0]{\n    asset->{\n      _id,\n      url\n    },\n    hotspot\n  },\n  stock\n}": PRODUCTS_BY_IDS_QUERYResult;
    "\n  *[\n    \n  _type == \"product\"\n  && store._ref == $storeId\n\n    && stock > 0\n    && stock <= 5\n  ]\n  | order(stock asc) {\n    _id,\n    name,\n    stock,\n    \"slug\": slug.current,\n    images[0]{ asset->{ url } }\n  }\n": LOW_STOCK_PRODUCTS_QUERYResult;
    "\n  *[\n    \n  _type == \"product\"\n  && store._ref == $storeId\n\n    && stock == 0\n  ]\n  | order(name asc) {\n    _id,\n    name,\n    \"slug\": slug.current,\n    images[0]{ asset->{ url } }\n  }\n": OUT_OF_STOCK_PRODUCTS_QUERYResult;
    "*[\n  _type == \"product\"\n  && (\n    $searchQuery == \"\"\n    || name match $searchQuery + \"*\"\n    || description match $searchQuery + \"*\"\n    || categories[0]->title match $searchQuery + \"*\"\n  )\n  && ($categorySlug == \"\" || categories[0]->slug.current == $categorySlug)\n  && ($material == \"\" || material == $material)\n  && ($color == \"\" || color == $color)\n  && ($minPrice == 0 || price >= $minPrice)\n  && ($maxPrice == 0 || price <= $maxPrice)\n] | order(name asc) [0...20] {\n  _id,\n  store->{\n    _id,\n    name,\n    username,\n    logo{\n      asset->{\n        _id,\n        url\n      }\n    }\n  },\n  name,\n  \"slug\": slug.current,\n  description,\n  price,\n  \"image\": images[0]{\n    asset->{\n      _id,\n      url\n    }\n  },\n  categories[0]->{\n    _id,\n    title,\n    \"slug\": slug.current\n  },\n  stock,\n  featured\n}": AI_SEARCH_PRODUCTS_QUERYResult;
    "count(*[_type == \"product\"])": PRODUCT_COUNT_QUERYResult;
    "count(*[_type == \"order\"])": ORDER_COUNT_QUERYResult;
    "math::sum(*[\n  _type == \"order\"\n  && status in [\"paid\", \"shipped\", \"delivered\"]\n].total)": TOTAL_REVENUE_QUERYResult;
    "*[\n  _type == \"order\"\n  && createdAt >= $startDate\n  && !(_id in path(\"drafts.**\"))\n] | order(createdAt desc) {\n  _id,\n  orderNumber,\n  total,\n  status,\n  createdAt,\n  \"itemCount\": count(items),\n  items[]{\n    quantity,\n    priceAtPurchase,\n    \"productName\": product->name,\n    \"productId\": product->_id\n  }\n}": ORDERS_LAST_7_DAYS_QUERYResult;
    "{\n  \"paid\": count(*[_type == \"order\" && status == \"paid\" && !(_id in path(\"drafts.**\"))]),\n  \"shipped\": count(*[_type == \"order\" && status == \"shipped\" && !(_id in path(\"drafts.**\"))]),\n  \"delivered\": count(*[_type == \"order\" && status == \"delivered\" && !(_id in path(\"drafts.**\"))]),\n  \"cancelled\": count(*[_type == \"order\" && status == \"cancelled\" && !(_id in path(\"drafts.**\"))])\n}": ORDER_STATUS_DISTRIBUTION_QUERYResult;
    "*[\n  _type == \"order\"\n  && status in [\"paid\", \"shipped\", \"delivered\"]\n  && !(_id in path(\"drafts.**\"))\n] {\n  items[]{\n    \"productId\": product->_id,\n    \"productName\": product->name,\n    \"productPrice\": product->price,\n    quantity\n  }\n}.items[]": TOP_SELLING_PRODUCTS_QUERYResult;
    "*[_type == \"product\"] {\n  _id,\n  name,\n  price,\n  stock,\n  \"category\": categories[0]->title\n}": PRODUCTS_INVENTORY_QUERYResult;
    "*[\n  _type == \"order\"\n  && status == \"paid\"\n  && !(_id in path(\"drafts.**\"))\n] | order(createdAt asc) {\n  _id,\n  orderNumber,\n  total,\n  createdAt,\n  email,\n  \"itemCount\": count(items)\n}": UNFULFILLED_ORDERS_QUERYResult;
    "{\n  \"currentPeriod\": math::sum(*[\n    _type == \"order\"\n    && status in [\"paid\", \"shipped\", \"delivered\"]\n    && createdAt >= $currentStart\n    && !(_id in path(\"drafts.**\"))\n  ].total),\n  \"previousPeriod\": math::sum(*[\n    _type == \"order\"\n    && status in [\"paid\", \"shipped\", \"delivered\"]\n    && createdAt >= $previousStart\n    && createdAt < $currentStart\n    && !(_id in path(\"drafts.**\"))\n  ].total),\n  \"currentOrderCount\": count(*[\n    _type == \"order\"\n    && createdAt >= $currentStart\n    && !(_id in path(\"drafts.**\"))\n  ]),\n  \"previousOrderCount\": count(*[\n    _type == \"order\"\n    && createdAt >= $previousStart\n    && createdAt < $currentStart\n    && !(_id in path(\"drafts.**\"))\n  ])\n}": REVENUE_BY_PERIOD_QUERYResult;
    "\n  *[_type == \"store\" && username == $username && activated == true][0]{\n    _id,\n    name,\n    description,\n    username,\n    address,\n    email,\n    contact,\n    status,\n    activated,\n    keywords,\n    categories,\n    types,\n    \"slug\": slug.current,\n    logo {\n      asset->{\n        _id,\n        url\n      }\n    }\n  }\n": STORE_BY_USERNAME_QUERYResult;
    "\n  *[_type == \"store\" && activated == true] | order(_createdAt desc){\n    _id,\n    name,\n    username,\n    description,\n    categories,\n    types,\n    \"slug\": slug.current,\n    logo {\n      asset->{\n        _id,\n        url\n      }\n    }\n  }\n": ALL_ACTIVE_STORES_QUERYResult;
    "\n  *[_type == \"store\" && userId == $userId] | order(_createdAt desc){\n    _id,\n    userId,\n    name,\n    username,\n    status,\n    activated,\n    categories,\n    types,\n    \"slug\": slug.current,\n    logo {\n      asset->{\n        _id,\n        url\n      }\n    }\n  }\n": STORES_BY_USER_QUERYResult;
    "\n  *[_type == \"store\" && slug.current == $slug][0]{\n    _id,\n    name,\n    description,\n    username,\n    address,\n    email,\n    contact,\n    status,\n    activated,\n    keywords,\n    categories,\n    types,\n    userId,\n    \"slug\": slug.current,\n    logo {\n      asset->{\n        _id,\n        url\n      }\n    }\n  }\n": STORE_BY_SLUG_QUERYResult;
    "\n  count(*[_type == \"store\" && username == $username])\n": STORE_EXISTS_BY_USERNAME_QUERYResult;
  }
}
