import { ReactNode } from "react";
import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import { ThemeProvider } from "next-themes";
import StoreProvider from "@/components/ui/providers/store-provider";
import { ConvexClientProvider } from "@/components/ui/providers/client-provider";
import { ClerkProvider } from "@clerk/nextjs";

const poppins = Poppins({
    subsets: ["latin"],
    weight: ["300","400","500","600","700"], // workaround TS + Turbo pack
    variable: "--font-poppins",
});

export const metadata: Metadata = {
    title: "zimapp platform",
    description: "Generated by the ZiMA Team Developers with their leading developer, Epreen Njolomole.",
    icons: "/logo.png",
};

export default function RootLayout({ children }: { children: ReactNode }) {
    return (
      <ClerkProvider>
        <ConvexClientProvider>
            <html lang="en" suppressHydrationWarning>
                <body className={cn('antialiased', poppins.variable)}>
                    <ThemeProvider attribute="class" defaultTheme="system" enableSystem disableTransitionOnChange>
                        <StoreProvider>{children}</StoreProvider>
                    </ThemeProvider>
                </body>
            </html>
        </ConvexClientProvider>
      </ClerkProvider>
    );
}