import { ReactNode } from "react";
import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import { ThemeProvider } from "next-themes";
import StoreProvider from "@/components/ui/providers/store-provider";
import { ConvexClientProvider } from "@/components/ui/providers/client-provider";
import { ClerkProvider } from "@clerk/nextjs";
import { ProfileSyncProvider } from "@/components/ui/providers/profile-syncing-provider";

const poppins = Poppins({
    subsets: ["latin"],
    weight: ["300","400","500","600","700"], // workaround TS + Turbo pack
    variable: "--font-poppins",
});

export const metadata: Metadata = {
    title: "zimapp platform",
    description: "Generated by the ZiMA Team Developers with their leading developer, Epreen Njolomole.",
    icons: "/logo.png",
};

export default function RootLayout({ children }: { children: ReactNode }) {
    return (
        <ClerkProvider
            appearance={{
                layout: {
                    socialButtonsPlacement: 'bottom'
                },
                theme: 'simple',
                variables: {
                    colorPrimary: "var(--billing-primary)",
                    colorPrimaryForeground: "var(--background)",
                    colorBackground: "var(--card)",
                    colorInputBackground: "var(--background)",
                    colorInputText: "var(--foreground)",
            
                    // Updated (deprecated → new)
                    colorForeground: "var(--foreground)",          // was colorText
                    colorMutedForeground: "var(--muted-foreground)",    // was colorTextSecondary
            
                    // These remain unchanged as instructed
                    colorShimmer: "var(--billing-primary)",
                    colorBorder: "var(--muted-foreground)",
                    colorMuted: "var(--card)",
            
                    fontFamily: "var(--font-poppins)"
                },
            }}        
        >
            <ConvexClientProvider>
                <html lang="en" suppressHydrationWarning>
                    <body className={cn('antialiased', poppins.variable)}>
                        <ThemeProvider attribute="class" defaultTheme="system" enableSystem disableTransitionOnChange>
                            <StoreProvider>
                                <ProfileSyncProvider>
                                    {children}
                                </ProfileSyncProvider>
                            </StoreProvider>
                        </ThemeProvider>
                    </body>
                </html>
            </ConvexClientProvider>
        </ClerkProvider>
    );
}