import { type Metadata } from 'next'
import { ReactNode } from 'react'
import { GalleryVerticalEnd } from "lucide-react"

export const metadata: Metadata = {
    title: "zimapp platform",
    description: "Generated by the ZiMA Team Developers with their leading developer, Epreen Njolomole.",
    icons: "/logo.png",
};

export default function SignupPage({
    children,
  }: Readonly<{
    children: ReactNode
  }>) {
  return (
    <div className="bg-background flex min-h-svh flex-col items-center justify-center gap-6">
      <div className="w-full">
        { children }
      </div>
    </div>
  )
}